"""initial schema

Revision ID: e18d331f40b3
Revises: 
Create Date: 2026-06-16 18:07:52.078419
"""
from alembic import op
import sqlalchemy as sa


revision = 'e18d331f40b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('league', sa.String(length=120), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=60), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_team', 'away_team', 'match_date', name='uq_match')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_match_status_date', ['status', 'match_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_away_team'), ['away_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team'), ['home_team'], unique=False)

    op.create_table('my_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=40), nullable=False),
    sa.Column('pick', sa.String(length=60), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('our_prob', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('kelly_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_win', sa.Float(), nullable=False),
    sa.Column('draw', sa.Float(), nullable=False),
    sa.Column('away_win', sa.Float(), nullable=False),
    sa.Column('predicted_outcome', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('missing_data', sa.JSON(), nullable=False),
    sa.Column('lambda_home', sa.Float(), nullable=False),
    sa.Column('lambda_away', sa.Float(), nullable=False),
    sa.Column('predicted_goals', sa.JSON(), nullable=False),
    sa.Column('most_likely_scores', sa.JSON(), nullable=False),
    sa.Column('markets', sa.JSON(), nullable=False),
    sa.Column('value_bets', sa.JSON(), nullable=False),
    sa.Column('poisson_matrix', sa.JSON(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('final_home_goals', sa.Integer(), nullable=False),
    sa.Column('final_away_goals', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('predictions')
    op.drop_table('my_tips')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_home_team'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team'))
        batch_op.drop_index('ix_match_status_date')

    op.drop_table('matches')
    # ### end Alembic commands ###
